// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtvyjibujkobeyeihrkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0dnlqaWJ1amtvYmV5ZWlocmt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODI0NzMsImV4cCI6MjA2NTQ1ODQ3M30.irdRf5LnyDbKrLPXhATafZ-O90qr9fgC7uuSvioEX0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);